---
- hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: add packages that I need
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - wget
        - git
        - vim
        - tree
        - htop
        - python-pip
        - reboot-notifier
        - curl
        - rsync
        - dirmngr
